### PR TITLE
Add setup.py

### LINKED ISSUE #28: Add ouroboros to the user's path automagically
Wanted to get this into an issue for discussion.

I'm planning to use `setuptools` in combination with `setup.py` to install ouroboros into the user's path at `pip install ...` time.

This will likely be a big refactor of `cli.py` and `main.py`, so to keep us all sane I'll probably split it into separate PRs.

### PR DESCRIPTION
**Pull request by tlkamp**
This PR makes `ouroboros` installable by pip. When ouroboros is installed by pip, `ouroboros` is available in the user's path.

There should be no notable difference in the documentation.

`run_tests.sh` still works.

Closes #28

### CODE REVIEW

**Comment by circa10a** [comment]
Should we modify the Travis build to push to pypi as well?

**Comment by tlkamp** [comment]
We could! Never done that before. Have you?

This also might be a major version bump.

**Comment by circa10a** [comment]
Yeah I have, It should actually still be in the history of the .travis.yml.
I'll see about getting it in there later on. At an event at the moment

**Comment by circa10a** [comment]
Also will need to update deploy.sh to get the package version from setup.py instead of __init__.py

**Pull request merged**
