### PR TITLE
Make CLI expose fewer globals, formatting

### PR DESCRIPTION
**Pull request by tlkamp**
Refactors a bit of the code (`cli.py` uses fewer globals, and other code no longer relies on those globals).

I ran `autopep8` against the files I worked in, please forgive me for the whitespace diffs

### CODE REVIEW

**Comment by tlkamp** [comment]
Will add more tests.

**Comment by circa10a** [comment]
> Will add more tests.

alt text

**Comment by circa10a** [comment]
@tlkamp since this is from `add-script-file`, this ready to merge?

**Comment by circa10a** [comment]
If so, bump the version in `__init__.py` and it can be deployed.

**Comment by tlkamp** [comment]
Yeah, ignore my shitty branch names

**Pull request merged**
